[package]
name = "node_element_hybrid"
version = "0.1.0"
authors = ["SyStem"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.5.13"
paho-mqtt = { path = "paho.mqtt.rust" }
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
strum_macros = "0.10.0"
rand = "0.5.5"
