[package]
name = "node_element_hybrid"
version = "0.1.0"
authors = ["SyStem"]
edition = "2018"

[dependencies]
log = "^0.4"
env_logger = "^0.7"
paho-mqtt = "^0.6"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
strum_macros = "^0.17"
rand = "^0.7"
